import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';

function RecentSales({ sales }) {
    return (
        <div className="bg-white rounded-2xl border border-gray-200/80 shadow-xs overflow-hidden flex flex-col justify-between">
            <div>
                <div className="p-5 border-b border-gray-100">
                    <h2 className="text-base font-bold text-gray-900">Recent Accounting Stream</h2>
                    <p className="text-xs text-gray-400">Latest 5 billing transactions generated by internal registers</p>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full border-collapse text-left">
                        <thead>
                            <tr className="bg-gray-50/70 border-b border-gray-200 text-[11px] font-bold text-gray-500 uppercase tracking-wider">
                                <th className="p-4">Asset Identification</th>
                                <th className="p-4">Units Sent</th>
                                <th className="p-4 text-right">Total Transacted</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 text-sm text-gray-600">
                            {sales.slice(0, 5).map((sale) => (
                                <tr key={sale.id} className="hover:bg-slate-50/50 transition-colors">
                                    <td className="p-4 font-semibold text-gray-900">
                                        {sale.medicine?.name || 'Unknown Item'}
                                    </td>
                                    <td className="p-4 font-mono text-gray-500">
                                        {sale.quantity}
                                    </td>
                                    <td className="p-4 text-right font-mono font-bold text-emerald-600">
                                        Rs. {sale.totalPrice?.toFixed(2)}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            <div className="p-4 bg-gray-50/40 border-t border-gray-100 text-center">
                <Link
                    to="/sales"
                    className="text-xs text-blue-600 hover:text-blue-700 font-medium transition-colors duration-150 inline-flex items-center gap-1"
                >
                    View Full Sales Journal →
                </Link>
            </div>
        </div>
    );
}

export default RecentSales;